require("settings.vimconfigs")
require("plugins.packer")
require("plugins.mason")
-- require("plugins.lsp")
require("plugins.lsp-saga")
require("plugins.lsp").setup()
require("plugins.lsp-installer")
require("plugins.flutter-tools")
require("plugins.telescope")
require("plugins.nerdcommenter")
require("plugins.nvimtree")
require("colorscheme.material")
require("keymaps.general")
